Clean with shellcheck

diff --git a/tapsig b/tapsig
--- a/tapsig
+++ b/tapsig
@@ -7,11 +7,11 @@ rc_plan=0
 tapsig_state="running"
 
 ok(){
-	printf "ok $plan${name+ $name}\n";
+	printf "ok %i%s\n" "$plan" "${name+ $name}"
 }
 
 not_ok(){
-	printf "not ok $plan${name+ $name}\n"
+	printf "not ok %i%s\n" "$plan" "${name+ $name}"
 }
 
 skip(){
@@ -30,15 +30,16 @@ depends_on(){
 
 skip_all(){
 	clean_up
-	printf "1..0 # SKIP${1+ $1}\n"
+	printf "1..0 # SKIP%s\n" "${1+ $1}"
 	exit 0
 }
 
+# shellcheck disable=SC2015
 check_expections(){
 	if [ "$plan" != 0 ];then
 		test_output stderr_plan stderr &&
 		test_output stdout_plan stdout &&
-		[ ${rc-0} -eq $rc_plan ] &&
+		[ "${rc-0}" -eq "$rc_plan" ] &&
 		ok ||
 		not_ok
 	fi
@@ -52,6 +53,7 @@ test_output(){
 	if cmp -s "$1" "$2";then
 		return 0
 	else
+		# shellcheck disable=SC2119
 		diff -u "$1" "$2" | diag
 		return 1
 	fi
@@ -65,10 +67,10 @@ tap(){
 	touch stdout_plan stderr_plan
 	plan=$(( plan + 1 ))
 	if [ -n "$skip" ];then
-		printf "ok $plan # SKIP $skip\n"
+		printf "ok %i # SKIP $skip\n" "$plan"
 		skip=""
 	elif [ -n "$todo" ];then
-		printf "not ok $plan # TODO $todo\n"
+		printf "not ok %i # TODO %s\n" "$plan" "$todo"
 		todo=""
 	else
 		"$@" > stdout 2> stderr
@@ -78,16 +80,17 @@ tap(){
 	clean_up
 }
 
+# shellcheck disable=SC2120
 diag(){
 	if [ -n "$1" ];then
-		printf "# $1\n"
+		printf "# %s\n" "$1"
 	else
 		sed 's/^/# /'
 	fi
 }
 
 bail_out(){
-	printf "Bail out!${1+ $1}\n"
+	printf "Bail out!%s\n" "${1+ $1}"
 	exit 0
 }
 
@@ -105,11 +108,11 @@ if [ -e "$1" ];then
 	current_dir=$(pwd)
 	work_dir="$HOME/.tapsig.$$"
 	if ! mkdir "$work_dir";then
-		printf "Can't create working directory $work_dir.\n" >&2
+		printf "Can't create working directory %s.\n" "$work_dir" >&2
 		exit 1
 	fi
-	if ! cd $work_dir;then
-		printf "Can't cd into working directory $work_dir.\n" >&2
+	if ! cd "$work_dir";then
+		printf "Can't cd into working directory %s.\n" "$work_dir" >&2
 		exit 1
 	fi
 
@@ -118,7 +121,7 @@ if [ -e "$1" ];then
 	rm -R "$work_dir"
 
 	if [ "$tapsig_state" = "done" ];then
-		printf "1..$plan\n"
+		printf "1..%s\n" "$plan"
 		exit 0
 	elif [ $plan -gt 0 ];then
 		printf "# Tests were run but done_testing() was not seen.\n" >&2
